(ns kubernetes.api.apps-v2
  (:require [kubernetes.api.openapiv2 :as openapiv2]
            [kubernetes.api.util :as util]))

(def make-context util/make-context)

(openapiv2/render-full-api "k8s-openapiv2")

; expose dynamically generated vars for static analysis
(declare
  create-admissionregistration-v1beta1mutating-webhook-configuration
  create-admissionregistration-v1beta1validating-webhook-configuration
  create-admissionregistration-v1mutating-webhook-configuration
  create-admissionregistration-v1validating-webhook-configuration
  create-apiextensions-v1beta1custom-resource-definition
  create-apiextensions-v1custom-resource-definition
  create-apiregistration-v1api-service
  create-apiregistration-v1beta1api-service
  create-apps-v1namespaced-controller-revision
  create-apps-v1namespaced-daemon-set
  create-apps-v1namespaced-deployment
  create-apps-v1namespaced-replica-set
  create-apps-v1namespaced-stateful-set
  create-auditregistration-v1alpha1audit-sink
  create-authentication-v1beta1token-review
  create-authentication-v1token-review
  create-authorization-v1beta1namespaced-local-subject-access-review
  create-authorization-v1beta1self-subject-access-review
  create-authorization-v1beta1self-subject-rules-review
  create-authorization-v1beta1subject-access-review
  create-authorization-v1namespaced-local-subject-access-review
  create-authorization-v1self-subject-access-review
  create-authorization-v1self-subject-rules-review
  create-authorization-v1subject-access-review
  create-autoscaling-v1namespaced-horizontal-pod-autoscaler
  create-autoscaling-v2beta1namespaced-horizontal-pod-autoscaler
  create-autoscaling-v2beta2namespaced-horizontal-pod-autoscaler
  create-batch-v1beta1namespaced-cron-job
  create-batch-v1namespaced-job
  create-batch-v2alpha1namespaced-cron-job
  create-certificates-v1beta1certificate-signing-request
  create-coordination-v1beta1namespaced-lease
  create-coordination-v1namespaced-lease
  create-core-v1namespace
  create-core-v1namespaced-binding
  create-core-v1namespaced-config-map
  create-core-v1namespaced-endpoints
  create-core-v1namespaced-event
  create-core-v1namespaced-limit-range
  create-core-v1namespaced-persistent-volume-claim
  create-core-v1namespaced-pod
  create-core-v1namespaced-pod-binding
  create-core-v1namespaced-pod-eviction
  create-core-v1namespaced-pod-template
  create-core-v1namespaced-replication-controller
  create-core-v1namespaced-resource-quota
  create-core-v1namespaced-secret
  create-core-v1namespaced-service
  create-core-v1namespaced-service-account
  create-core-v1namespaced-service-account-token
  create-core-v1node
  create-core-v1persistent-volume
  create-discovery-v1beta1namespaced-endpoint-slice
  create-events-v1beta1namespaced-event
  create-extensions-v1beta1namespaced-ingress
  create-flowcontrol-apiserver-v1alpha1flow-schema
  create-flowcontrol-apiserver-v1alpha1priority-level-configuration
  create-networking-v1beta1namespaced-ingress
  create-networking-v1namespaced-network-policy
  create-node-v1alpha1runtime-class
  create-node-v1beta1runtime-class
  create-policy-v1beta1namespaced-pod-disruption-budget
  create-policy-v1beta1pod-security-policy
  create-rbac-authorization-v1alpha1cluster-role
  create-rbac-authorization-v1alpha1cluster-role-binding
  create-rbac-authorization-v1alpha1namespaced-role
  create-rbac-authorization-v1alpha1namespaced-role-binding
  create-rbac-authorization-v1beta1cluster-role
  create-rbac-authorization-v1beta1cluster-role-binding
  create-rbac-authorization-v1beta1namespaced-role
  create-rbac-authorization-v1beta1namespaced-role-binding
  create-rbac-authorization-v1cluster-role
  create-rbac-authorization-v1cluster-role-binding
  create-rbac-authorization-v1namespaced-role
  create-rbac-authorization-v1namespaced-role-binding
  create-scheduling-v1alpha1priority-class
  create-scheduling-v1beta1priority-class
  create-scheduling-v1priority-class
  create-settings-v1alpha1namespaced-pod-preset
  create-storage-v1alpha1volume-attachment
  create-storage-v1beta1csi-driver
  create-storage-v1beta1csi-node
  create-storage-v1beta1storage-class
  create-storage-v1beta1volume-attachment
  create-storage-v1csi-node
  create-storage-v1storage-class
  create-storage-v1volume-attachment
  delete-admissionregistration-v1beta1collection-mutating-webhook-configuration
  delete-admissionregistration-v1beta1collection-validating-webhook-configuration
  delete-admissionregistration-v1beta1mutating-webhook-configuration
  delete-admissionregistration-v1beta1validating-webhook-configuration
  delete-admissionregistration-v1collection-mutating-webhook-configuration
  delete-admissionregistration-v1collection-validating-webhook-configuration
  delete-admissionregistration-v1mutating-webhook-configuration
  delete-admissionregistration-v1validating-webhook-configuration
  delete-apiextensions-v1beta1collection-custom-resource-definition
  delete-apiextensions-v1beta1custom-resource-definition
  delete-apiextensions-v1collection-custom-resource-definition
  delete-apiextensions-v1custom-resource-definition
  delete-apiregistration-v1api-service
  delete-apiregistration-v1beta1api-service
  delete-apiregistration-v1beta1collection-api-service
  delete-apiregistration-v1collection-api-service
  delete-apps-v1collection-namespaced-controller-revision
  delete-apps-v1collection-namespaced-daemon-set
  delete-apps-v1collection-namespaced-deployment
  delete-apps-v1collection-namespaced-replica-set
  delete-apps-v1collection-namespaced-stateful-set
  delete-apps-v1namespaced-controller-revision
  delete-apps-v1namespaced-daemon-set
  delete-apps-v1namespaced-deployment
  delete-apps-v1namespaced-replica-set
  delete-apps-v1namespaced-stateful-set
  delete-auditregistration-v1alpha1audit-sink
  delete-auditregistration-v1alpha1collection-audit-sink
  delete-autoscaling-v1collection-namespaced-horizontal-pod-autoscaler
  delete-autoscaling-v1namespaced-horizontal-pod-autoscaler
  delete-autoscaling-v2beta1collection-namespaced-horizontal-pod-autoscaler
  delete-autoscaling-v2beta1namespaced-horizontal-pod-autoscaler
  delete-autoscaling-v2beta2collection-namespaced-horizontal-pod-autoscaler
  delete-autoscaling-v2beta2namespaced-horizontal-pod-autoscaler
  delete-batch-v1beta1collection-namespaced-cron-job
  delete-batch-v1beta1namespaced-cron-job
  delete-batch-v1collection-namespaced-job
  delete-batch-v1namespaced-job
  delete-batch-v2alpha1collection-namespaced-cron-job
  delete-batch-v2alpha1namespaced-cron-job
  delete-certificates-v1beta1certificate-signing-request
  delete-certificates-v1beta1collection-certificate-signing-request
  delete-coordination-v1beta1collection-namespaced-lease
  delete-coordination-v1beta1namespaced-lease
  delete-coordination-v1collection-namespaced-lease
  delete-coordination-v1namespaced-lease
  delete-core-v1collection-namespaced-config-map
  delete-core-v1collection-namespaced-endpoints
  delete-core-v1collection-namespaced-event
  delete-core-v1collection-namespaced-limit-range
  delete-core-v1collection-namespaced-persistent-volume-claim
  delete-core-v1collection-namespaced-pod
  delete-core-v1collection-namespaced-pod-template
  delete-core-v1collection-namespaced-replication-controller
  delete-core-v1collection-namespaced-resource-quota
  delete-core-v1collection-namespaced-secret
  delete-core-v1collection-namespaced-service-account
  delete-core-v1collection-node
  delete-core-v1collection-persistent-volume
  delete-core-v1namespace
  delete-core-v1namespaced-config-map
  delete-core-v1namespaced-endpoints
  delete-core-v1namespaced-event
  delete-core-v1namespaced-limit-range
  delete-core-v1namespaced-persistent-volume-claim
  delete-core-v1namespaced-pod
  delete-core-v1namespaced-pod-template
  delete-core-v1namespaced-replication-controller
  delete-core-v1namespaced-resource-quota
  delete-core-v1namespaced-secret
  delete-core-v1namespaced-service
  delete-core-v1namespaced-service-account
  delete-core-v1node
  delete-core-v1persistent-volume
  delete-discovery-v1beta1collection-namespaced-endpoint-slice
  delete-discovery-v1beta1namespaced-endpoint-slice
  delete-events-v1beta1collection-namespaced-event
  delete-events-v1beta1namespaced-event
  delete-extensions-v1beta1collection-namespaced-ingress
  delete-extensions-v1beta1namespaced-ingress
  delete-flowcontrol-apiserver-v1alpha1collection-flow-schema
  delete-flowcontrol-apiserver-v1alpha1collection-priority-level-configuration
  delete-flowcontrol-apiserver-v1alpha1flow-schema
  delete-flowcontrol-apiserver-v1alpha1priority-level-configuration
  delete-networking-v1beta1collection-namespaced-ingress
  delete-networking-v1beta1namespaced-ingress
  delete-networking-v1collection-namespaced-network-policy
  delete-networking-v1namespaced-network-policy
  delete-node-v1alpha1collection-runtime-class
  delete-node-v1alpha1runtime-class
  delete-node-v1beta1collection-runtime-class
  delete-node-v1beta1runtime-class
  delete-policy-v1beta1collection-namespaced-pod-disruption-budget
  delete-policy-v1beta1collection-pod-security-policy
  delete-policy-v1beta1namespaced-pod-disruption-budget
  delete-policy-v1beta1pod-security-policy
  delete-rbac-authorization-v1alpha1cluster-role
  delete-rbac-authorization-v1alpha1cluster-role-binding
  delete-rbac-authorization-v1alpha1collection-cluster-role
  delete-rbac-authorization-v1alpha1collection-cluster-role-binding
  delete-rbac-authorization-v1alpha1collection-namespaced-role
  delete-rbac-authorization-v1alpha1collection-namespaced-role-binding
  delete-rbac-authorization-v1alpha1namespaced-role
  delete-rbac-authorization-v1alpha1namespaced-role-binding
  delete-rbac-authorization-v1beta1cluster-role
  delete-rbac-authorization-v1beta1cluster-role-binding
  delete-rbac-authorization-v1beta1collection-cluster-role
  delete-rbac-authorization-v1beta1collection-cluster-role-binding
  delete-rbac-authorization-v1beta1collection-namespaced-role
  delete-rbac-authorization-v1beta1collection-namespaced-role-binding
  delete-rbac-authorization-v1beta1namespaced-role
  delete-rbac-authorization-v1beta1namespaced-role-binding
  delete-rbac-authorization-v1cluster-role
  delete-rbac-authorization-v1cluster-role-binding
  delete-rbac-authorization-v1collection-cluster-role
  delete-rbac-authorization-v1collection-cluster-role-binding
  delete-rbac-authorization-v1collection-namespaced-role
  delete-rbac-authorization-v1collection-namespaced-role-binding
  delete-rbac-authorization-v1namespaced-role
  delete-rbac-authorization-v1namespaced-role-binding
  delete-scheduling-v1alpha1collection-priority-class
  delete-scheduling-v1alpha1priority-class
  delete-scheduling-v1beta1collection-priority-class
  delete-scheduling-v1beta1priority-class
  delete-scheduling-v1collection-priority-class
  delete-scheduling-v1priority-class
  delete-settings-v1alpha1collection-namespaced-pod-preset
  delete-settings-v1alpha1namespaced-pod-preset
  delete-storage-v1alpha1collection-volume-attachment
  delete-storage-v1alpha1volume-attachment
  delete-storage-v1beta1collection-csi-driver
  delete-storage-v1beta1collection-csi-node
  delete-storage-v1beta1collection-storage-class
  delete-storage-v1beta1collection-volume-attachment
  delete-storage-v1beta1csi-driver
  delete-storage-v1beta1csi-node
  delete-storage-v1beta1storage-class
  delete-storage-v1beta1volume-attachment
  delete-storage-v1collection-csi-node
  delete-storage-v1collection-storage-class
  delete-storage-v1collection-volume-attachment
  delete-storage-v1csi-node
  delete-storage-v1storage-class
  delete-storage-v1volume-attachment
  get-admissionregistration-api-group
  get-admissionregistration-v1api-resources
  get-admissionregistration-v1beta1api-resources
  get-api-versions
  get-apiextensions-api-group
  get-apiextensions-v1api-resources
  get-apiextensions-v1beta1api-resources
  get-apiregistration-api-group
  get-apiregistration-v1api-resources
  get-apiregistration-v1beta1api-resources
  get-apps-api-group
  get-apps-v1api-resources
  get-auditregistration-api-group
  get-auditregistration-v1alpha1api-resources
  get-authentication-api-group
  get-authentication-v1api-resources
  get-authentication-v1beta1api-resources
  get-authorization-api-group
  get-authorization-v1api-resources
  get-authorization-v1beta1api-resources
  get-autoscaling-api-group
  get-autoscaling-v1api-resources
  get-autoscaling-v2beta1api-resources
  get-autoscaling-v2beta2api-resources
  get-batch-api-group
  get-batch-v1api-resources
  get-batch-v1beta1api-resources
  get-batch-v2alpha1api-resources
  get-certificates-api-group
  get-certificates-v1beta1api-resources
  get-code-version
  get-coordination-api-group
  get-coordination-v1api-resources
  get-coordination-v1beta1api-resources
  get-core-api-versions
  get-core-v1api-resources
  get-discovery-api-group
  get-discovery-v1beta1api-resources
  get-events-api-group
  get-events-v1beta1api-resources
  get-extensions-api-group
  get-extensions-v1beta1api-resources
  get-flowcontrol-apiserver-api-group
  get-flowcontrol-apiserver-v1alpha1api-resources
  get-networking-api-group
  get-networking-v1api-resources
  get-networking-v1beta1api-resources
  get-node-api-group
  get-node-v1alpha1api-resources
  get-node-v1beta1api-resources
  get-policy-api-group
  get-policy-v1beta1api-resources
  get-rbac-authorization-api-group
  get-rbac-authorization-v1alpha1api-resources
  get-rbac-authorization-v1api-resources
  get-rbac-authorization-v1beta1api-resources
  get-scheduling-api-group
  get-scheduling-v1alpha1api-resources
  get-scheduling-v1api-resources
  get-scheduling-v1beta1api-resources
  get-settings-api-group
  get-settings-v1alpha1api-resources
  get-storage-api-group
  get-storage-v1alpha1api-resources
  get-storage-v1api-resources
  get-storage-v1beta1api-resources
  list-admissionregistration-v1beta1mutating-webhook-configuration
  list-admissionregistration-v1beta1validating-webhook-configuration
  list-admissionregistration-v1mutating-webhook-configuration
  list-admissionregistration-v1validating-webhook-configuration
  list-apiextensions-v1beta1custom-resource-definition
  list-apiextensions-v1custom-resource-definition
  list-apiregistration-v1api-service
  list-apiregistration-v1beta1api-service
  list-apps-v1controller-revision-for-all-namespaces
  list-apps-v1daemon-set-for-all-namespaces
  list-apps-v1deployment-for-all-namespaces
  list-apps-v1namespaced-controller-revision
  list-apps-v1namespaced-daemon-set
  list-apps-v1namespaced-deployment
  list-apps-v1namespaced-replica-set
  list-apps-v1namespaced-stateful-set
  list-apps-v1replica-set-for-all-namespaces
  list-apps-v1stateful-set-for-all-namespaces
  list-auditregistration-v1alpha1audit-sink
  list-autoscaling-v1horizontal-pod-autoscaler-for-all-namespaces
  list-autoscaling-v1namespaced-horizontal-pod-autoscaler
  list-autoscaling-v2beta1horizontal-pod-autoscaler-for-all-namespaces
  list-autoscaling-v2beta1namespaced-horizontal-pod-autoscaler
  list-autoscaling-v2beta2horizontal-pod-autoscaler-for-all-namespaces
  list-autoscaling-v2beta2namespaced-horizontal-pod-autoscaler
  list-batch-v1beta1cron-job-for-all-namespaces
  list-batch-v1beta1namespaced-cron-job
  list-batch-v1job-for-all-namespaces
  list-batch-v1namespaced-job
  list-batch-v2alpha1cron-job-for-all-namespaces
  list-batch-v2alpha1namespaced-cron-job
  list-certificates-v1beta1certificate-signing-request
  list-coordination-v1beta1lease-for-all-namespaces
  list-coordination-v1beta1namespaced-lease
  list-coordination-v1lease-for-all-namespaces
  list-coordination-v1namespaced-lease
  list-core-v1component-status
  list-core-v1config-map-for-all-namespaces
  list-core-v1endpoints-for-all-namespaces
  list-core-v1event-for-all-namespaces
  list-core-v1limit-range-for-all-namespaces
  list-core-v1namespace
  list-core-v1namespaced-config-map
  list-core-v1namespaced-endpoints
  list-core-v1namespaced-event
  list-core-v1namespaced-limit-range
  list-core-v1namespaced-persistent-volume-claim
  list-core-v1namespaced-pod
  list-core-v1namespaced-pod-template
  list-core-v1namespaced-replication-controller
  list-core-v1namespaced-resource-quota
  list-core-v1namespaced-secret
  list-core-v1namespaced-service
  list-core-v1namespaced-service-account
  list-core-v1node
  list-core-v1persistent-volume
  list-core-v1persistent-volume-claim-for-all-namespaces
  list-core-v1pod-for-all-namespaces
  list-core-v1pod-template-for-all-namespaces
  list-core-v1replication-controller-for-all-namespaces
  list-core-v1resource-quota-for-all-namespaces
  list-core-v1secret-for-all-namespaces
  list-core-v1service-account-for-all-namespaces
  list-core-v1service-for-all-namespaces
  list-discovery-v1beta1endpoint-slice-for-all-namespaces
  list-discovery-v1beta1namespaced-endpoint-slice
  list-events-v1beta1event-for-all-namespaces
  list-events-v1beta1namespaced-event
  list-extensions-v1beta1ingress-for-all-namespaces
  list-extensions-v1beta1namespaced-ingress
  list-flowcontrol-apiserver-v1alpha1flow-schema
  list-flowcontrol-apiserver-v1alpha1priority-level-configuration
  list-networking-v1beta1ingress-for-all-namespaces
  list-networking-v1beta1namespaced-ingress
  list-networking-v1namespaced-network-policy
  list-networking-v1network-policy-for-all-namespaces
  list-node-v1alpha1runtime-class
  list-node-v1beta1runtime-class
  list-policy-v1beta1namespaced-pod-disruption-budget
  list-policy-v1beta1pod-disruption-budget-for-all-namespaces
  list-policy-v1beta1pod-security-policy
  list-rbac-authorization-v1alpha1cluster-role
  list-rbac-authorization-v1alpha1cluster-role-binding
  list-rbac-authorization-v1alpha1namespaced-role
  list-rbac-authorization-v1alpha1namespaced-role-binding
  list-rbac-authorization-v1alpha1role-binding-for-all-namespaces
  list-rbac-authorization-v1alpha1role-for-all-namespaces
  list-rbac-authorization-v1beta1cluster-role
  list-rbac-authorization-v1beta1cluster-role-binding
  list-rbac-authorization-v1beta1namespaced-role
  list-rbac-authorization-v1beta1namespaced-role-binding
  list-rbac-authorization-v1beta1role-binding-for-all-namespaces
  list-rbac-authorization-v1beta1role-for-all-namespaces
  list-rbac-authorization-v1cluster-role
  list-rbac-authorization-v1cluster-role-binding
  list-rbac-authorization-v1namespaced-role
  list-rbac-authorization-v1namespaced-role-binding
  list-rbac-authorization-v1role-binding-for-all-namespaces
  list-rbac-authorization-v1role-for-all-namespaces
  list-scheduling-v1alpha1priority-class
  list-scheduling-v1beta1priority-class
  list-scheduling-v1priority-class
  list-settings-v1alpha1namespaced-pod-preset
  list-settings-v1alpha1pod-preset-for-all-namespaces
  list-storage-v1alpha1volume-attachment
  list-storage-v1beta1csi-driver
  list-storage-v1beta1csi-node
  list-storage-v1beta1storage-class
  list-storage-v1beta1volume-attachment
  list-storage-v1csi-node
  list-storage-v1storage-class
  list-storage-v1volume-attachment
  make-context
  patch-admissionregistration-v1beta1mutating-webhook-configuration
  patch-admissionregistration-v1beta1validating-webhook-configuration
  patch-admissionregistration-v1mutating-webhook-configuration
  patch-admissionregistration-v1validating-webhook-configuration
  patch-apiextensions-v1beta1custom-resource-definition
  patch-apiextensions-v1beta1custom-resource-definition-status
  patch-apiextensions-v1custom-resource-definition
  patch-apiextensions-v1custom-resource-definition-status
  patch-apiregistration-v1api-service
  patch-apiregistration-v1api-service-status
  patch-apiregistration-v1beta1api-service
  patch-apiregistration-v1beta1api-service-status
  patch-apps-v1namespaced-controller-revision
  patch-apps-v1namespaced-daemon-set
  patch-apps-v1namespaced-daemon-set-status
  patch-apps-v1namespaced-deployment
  patch-apps-v1namespaced-deployment-scale
  patch-apps-v1namespaced-deployment-status
  patch-apps-v1namespaced-replica-set
  patch-apps-v1namespaced-replica-set-scale
  patch-apps-v1namespaced-replica-set-status
  patch-apps-v1namespaced-stateful-set
  patch-apps-v1namespaced-stateful-set-scale
  patch-apps-v1namespaced-stateful-set-status
  patch-auditregistration-v1alpha1audit-sink
  patch-autoscaling-v1namespaced-horizontal-pod-autoscaler
  patch-autoscaling-v1namespaced-horizontal-pod-autoscaler-status
  patch-autoscaling-v2beta1namespaced-horizontal-pod-autoscaler
  patch-autoscaling-v2beta1namespaced-horizontal-pod-autoscaler-status
  patch-autoscaling-v2beta2namespaced-horizontal-pod-autoscaler
  patch-autoscaling-v2beta2namespaced-horizontal-pod-autoscaler-status
  patch-batch-v1beta1namespaced-cron-job
  patch-batch-v1beta1namespaced-cron-job-status
  patch-batch-v1namespaced-job
  patch-batch-v1namespaced-job-status
  patch-batch-v2alpha1namespaced-cron-job
  patch-batch-v2alpha1namespaced-cron-job-status
  patch-certificates-v1beta1certificate-signing-request
  patch-certificates-v1beta1certificate-signing-request-status
  patch-coordination-v1beta1namespaced-lease
  patch-coordination-v1namespaced-lease
  patch-core-v1namespace
  patch-core-v1namespace-status
  patch-core-v1namespaced-config-map
  patch-core-v1namespaced-endpoints
  patch-core-v1namespaced-event
  patch-core-v1namespaced-limit-range
  patch-core-v1namespaced-persistent-volume-claim
  patch-core-v1namespaced-persistent-volume-claim-status
  patch-core-v1namespaced-pod
  patch-core-v1namespaced-pod-status
  patch-core-v1namespaced-pod-template
  patch-core-v1namespaced-replication-controller
  patch-core-v1namespaced-replication-controller-scale
  patch-core-v1namespaced-replication-controller-status
  patch-core-v1namespaced-resource-quota
  patch-core-v1namespaced-resource-quota-status
  patch-core-v1namespaced-secret
  patch-core-v1namespaced-service
  patch-core-v1namespaced-service-account
  patch-core-v1namespaced-service-status
  patch-core-v1node
  patch-core-v1node-status
  patch-core-v1persistent-volume
  patch-core-v1persistent-volume-status
  patch-discovery-v1beta1namespaced-endpoint-slice
  patch-events-v1beta1namespaced-event
  patch-extensions-v1beta1namespaced-ingress
  patch-extensions-v1beta1namespaced-ingress-status
  patch-flowcontrol-apiserver-v1alpha1flow-schema
  patch-flowcontrol-apiserver-v1alpha1flow-schema-status
  patch-flowcontrol-apiserver-v1alpha1priority-level-configuration
  patch-flowcontrol-apiserver-v1alpha1priority-level-configuration-status
  patch-networking-v1beta1namespaced-ingress
  patch-networking-v1beta1namespaced-ingress-status
  patch-networking-v1namespaced-network-policy
  patch-node-v1alpha1runtime-class
  patch-node-v1beta1runtime-class
  patch-policy-v1beta1namespaced-pod-disruption-budget
  patch-policy-v1beta1namespaced-pod-disruption-budget-status
  patch-policy-v1beta1pod-security-policy
  patch-rbac-authorization-v1alpha1cluster-role
  patch-rbac-authorization-v1alpha1cluster-role-binding
  patch-rbac-authorization-v1alpha1namespaced-role
  patch-rbac-authorization-v1alpha1namespaced-role-binding
  patch-rbac-authorization-v1beta1cluster-role
  patch-rbac-authorization-v1beta1cluster-role-binding
  patch-rbac-authorization-v1beta1namespaced-role
  patch-rbac-authorization-v1beta1namespaced-role-binding
  patch-rbac-authorization-v1cluster-role
  patch-rbac-authorization-v1cluster-role-binding
  patch-rbac-authorization-v1namespaced-role
  patch-rbac-authorization-v1namespaced-role-binding
  patch-scheduling-v1alpha1priority-class
  patch-scheduling-v1beta1priority-class
  patch-scheduling-v1priority-class
  patch-settings-v1alpha1namespaced-pod-preset
  patch-storage-v1alpha1volume-attachment
  patch-storage-v1beta1csi-driver
  patch-storage-v1beta1csi-node
  patch-storage-v1beta1storage-class
  patch-storage-v1beta1volume-attachment
  patch-storage-v1csi-node
  patch-storage-v1storage-class
  patch-storage-v1volume-attachment
  patch-storage-v1volume-attachment-status
  read-admissionregistration-v1beta1mutating-webhook-configuration
  read-admissionregistration-v1beta1validating-webhook-configuration
  read-admissionregistration-v1mutating-webhook-configuration
  read-admissionregistration-v1validating-webhook-configuration
  read-apiextensions-v1beta1custom-resource-definition
  read-apiextensions-v1beta1custom-resource-definition-status
  read-apiextensions-v1custom-resource-definition
  read-apiextensions-v1custom-resource-definition-status
  read-apiregistration-v1api-service
  read-apiregistration-v1api-service-status
  read-apiregistration-v1beta1api-service
  read-apiregistration-v1beta1api-service-status
  read-apps-v1namespaced-controller-revision
  read-apps-v1namespaced-daemon-set
  read-apps-v1namespaced-daemon-set-status
  read-apps-v1namespaced-deployment
  read-apps-v1namespaced-deployment-scale
  read-apps-v1namespaced-deployment-status
  read-apps-v1namespaced-replica-set
  read-apps-v1namespaced-replica-set-scale
  read-apps-v1namespaced-replica-set-status
  read-apps-v1namespaced-stateful-set
  read-apps-v1namespaced-stateful-set-scale
  read-apps-v1namespaced-stateful-set-status
  read-auditregistration-v1alpha1audit-sink
  read-autoscaling-v1namespaced-horizontal-pod-autoscaler
  read-autoscaling-v1namespaced-horizontal-pod-autoscaler-status
  read-autoscaling-v2beta1namespaced-horizontal-pod-autoscaler
  read-autoscaling-v2beta1namespaced-horizontal-pod-autoscaler-status
  read-autoscaling-v2beta2namespaced-horizontal-pod-autoscaler
  read-autoscaling-v2beta2namespaced-horizontal-pod-autoscaler-status
  read-batch-v1beta1namespaced-cron-job
  read-batch-v1beta1namespaced-cron-job-status
  read-batch-v1namespaced-job
  read-batch-v1namespaced-job-status
  read-batch-v2alpha1namespaced-cron-job
  read-batch-v2alpha1namespaced-cron-job-status
  read-certificates-v1beta1certificate-signing-request
  read-certificates-v1beta1certificate-signing-request-status
  read-coordination-v1beta1namespaced-lease
  read-coordination-v1namespaced-lease
  read-core-v1component-status
  read-core-v1namespace
  read-core-v1namespace-status
  read-core-v1namespaced-config-map
  read-core-v1namespaced-endpoints
  read-core-v1namespaced-event
  read-core-v1namespaced-limit-range
  read-core-v1namespaced-persistent-volume-claim
  read-core-v1namespaced-persistent-volume-claim-status
  read-core-v1namespaced-pod
  read-core-v1namespaced-pod-log
  read-core-v1namespaced-pod-status
  read-core-v1namespaced-pod-template
  read-core-v1namespaced-replication-controller
  read-core-v1namespaced-replication-controller-scale
  read-core-v1namespaced-replication-controller-status
  read-core-v1namespaced-resource-quota
  read-core-v1namespaced-resource-quota-status
  read-core-v1namespaced-secret
  read-core-v1namespaced-service
  read-core-v1namespaced-service-account
  read-core-v1namespaced-service-status
  read-core-v1node
  read-core-v1node-status
  read-core-v1persistent-volume
  read-core-v1persistent-volume-status
  read-discovery-v1beta1namespaced-endpoint-slice
  read-events-v1beta1namespaced-event
  read-extensions-v1beta1namespaced-ingress
  read-extensions-v1beta1namespaced-ingress-status
  read-flowcontrol-apiserver-v1alpha1flow-schema
  read-flowcontrol-apiserver-v1alpha1flow-schema-status
  read-flowcontrol-apiserver-v1alpha1priority-level-configuration
  read-flowcontrol-apiserver-v1alpha1priority-level-configuration-status
  read-networking-v1beta1namespaced-ingress
  read-networking-v1beta1namespaced-ingress-status
  read-networking-v1namespaced-network-policy
  read-node-v1alpha1runtime-class
  read-node-v1beta1runtime-class
  read-policy-v1beta1namespaced-pod-disruption-budget
  read-policy-v1beta1namespaced-pod-disruption-budget-status
  read-policy-v1beta1pod-security-policy
  read-rbac-authorization-v1alpha1cluster-role
  read-rbac-authorization-v1alpha1cluster-role-binding
  read-rbac-authorization-v1alpha1namespaced-role
  read-rbac-authorization-v1alpha1namespaced-role-binding
  read-rbac-authorization-v1beta1cluster-role
  read-rbac-authorization-v1beta1cluster-role-binding
  read-rbac-authorization-v1beta1namespaced-role
  read-rbac-authorization-v1beta1namespaced-role-binding
  read-rbac-authorization-v1cluster-role
  read-rbac-authorization-v1cluster-role-binding
  read-rbac-authorization-v1namespaced-role
  read-rbac-authorization-v1namespaced-role-binding
  read-scheduling-v1alpha1priority-class
  read-scheduling-v1beta1priority-class
  read-scheduling-v1priority-class
  read-settings-v1alpha1namespaced-pod-preset
  read-storage-v1alpha1volume-attachment
  read-storage-v1beta1csi-driver
  read-storage-v1beta1csi-node
  read-storage-v1beta1storage-class
  read-storage-v1beta1volume-attachment
  read-storage-v1csi-node
  read-storage-v1storage-class
  read-storage-v1volume-attachment
  read-storage-v1volume-attachment-status
  replace-admissionregistration-v1beta1mutating-webhook-configuration
  replace-admissionregistration-v1beta1validating-webhook-configuration
  replace-admissionregistration-v1mutating-webhook-configuration
  replace-admissionregistration-v1validating-webhook-configuration
  replace-apiextensions-v1beta1custom-resource-definition
  replace-apiextensions-v1beta1custom-resource-definition-status
  replace-apiextensions-v1custom-resource-definition
  replace-apiextensions-v1custom-resource-definition-status
  replace-apiregistration-v1api-service
  replace-apiregistration-v1api-service-status
  replace-apiregistration-v1beta1api-service
  replace-apiregistration-v1beta1api-service-status
  replace-apps-v1namespaced-controller-revision
  replace-apps-v1namespaced-daemon-set
  replace-apps-v1namespaced-daemon-set-status
  replace-apps-v1namespaced-deployment
  replace-apps-v1namespaced-deployment-scale
  replace-apps-v1namespaced-deployment-status
  replace-apps-v1namespaced-replica-set
  replace-apps-v1namespaced-replica-set-scale
  replace-apps-v1namespaced-replica-set-status
  replace-apps-v1namespaced-stateful-set
  replace-apps-v1namespaced-stateful-set-scale
  replace-apps-v1namespaced-stateful-set-status
  replace-auditregistration-v1alpha1audit-sink
  replace-autoscaling-v1namespaced-horizontal-pod-autoscaler
  replace-autoscaling-v1namespaced-horizontal-pod-autoscaler-status
  replace-autoscaling-v2beta1namespaced-horizontal-pod-autoscaler
  replace-autoscaling-v2beta1namespaced-horizontal-pod-autoscaler-status
  replace-autoscaling-v2beta2namespaced-horizontal-pod-autoscaler
  replace-autoscaling-v2beta2namespaced-horizontal-pod-autoscaler-status
  replace-batch-v1beta1namespaced-cron-job
  replace-batch-v1beta1namespaced-cron-job-status
  replace-batch-v1namespaced-job
  replace-batch-v1namespaced-job-status
  replace-batch-v2alpha1namespaced-cron-job
  replace-batch-v2alpha1namespaced-cron-job-status
  replace-certificates-v1beta1certificate-signing-request
  replace-certificates-v1beta1certificate-signing-request-approval
  replace-certificates-v1beta1certificate-signing-request-status
  replace-coordination-v1beta1namespaced-lease
  replace-coordination-v1namespaced-lease
  replace-core-v1namespace
  replace-core-v1namespace-finalize
  replace-core-v1namespace-status
  replace-core-v1namespaced-config-map
  replace-core-v1namespaced-endpoints
  replace-core-v1namespaced-event
  replace-core-v1namespaced-limit-range
  replace-core-v1namespaced-persistent-volume-claim
  replace-core-v1namespaced-persistent-volume-claim-status
  replace-core-v1namespaced-pod
  replace-core-v1namespaced-pod-status
  replace-core-v1namespaced-pod-template
  replace-core-v1namespaced-replication-controller
  replace-core-v1namespaced-replication-controller-scale
  replace-core-v1namespaced-replication-controller-status
  replace-core-v1namespaced-resource-quota
  replace-core-v1namespaced-resource-quota-status
  replace-core-v1namespaced-secret
  replace-core-v1namespaced-service
  replace-core-v1namespaced-service-account
  replace-core-v1namespaced-service-status
  replace-core-v1node
  replace-core-v1node-status
  replace-core-v1persistent-volume
  replace-core-v1persistent-volume-status
  replace-discovery-v1beta1namespaced-endpoint-slice
  replace-events-v1beta1namespaced-event
  replace-extensions-v1beta1namespaced-ingress
  replace-extensions-v1beta1namespaced-ingress-status
  replace-flowcontrol-apiserver-v1alpha1flow-schema
  replace-flowcontrol-apiserver-v1alpha1flow-schema-status
  replace-flowcontrol-apiserver-v1alpha1priority-level-configuration
  replace-flowcontrol-apiserver-v1alpha1priority-level-configuration-status
  replace-networking-v1beta1namespaced-ingress
  replace-networking-v1beta1namespaced-ingress-status
  replace-networking-v1namespaced-network-policy
  replace-node-v1alpha1runtime-class
  replace-node-v1beta1runtime-class
  replace-policy-v1beta1namespaced-pod-disruption-budget
  replace-policy-v1beta1namespaced-pod-disruption-budget-status
  replace-policy-v1beta1pod-security-policy
  replace-rbac-authorization-v1alpha1cluster-role
  replace-rbac-authorization-v1alpha1cluster-role-binding
  replace-rbac-authorization-v1alpha1namespaced-role
  replace-rbac-authorization-v1alpha1namespaced-role-binding
  replace-rbac-authorization-v1beta1cluster-role
  replace-rbac-authorization-v1beta1cluster-role-binding
  replace-rbac-authorization-v1beta1namespaced-role
  replace-rbac-authorization-v1beta1namespaced-role-binding
  replace-rbac-authorization-v1cluster-role
  replace-rbac-authorization-v1cluster-role-binding
  replace-rbac-authorization-v1namespaced-role
  replace-rbac-authorization-v1namespaced-role-binding
  replace-scheduling-v1alpha1priority-class
  replace-scheduling-v1beta1priority-class
  replace-scheduling-v1priority-class
  replace-settings-v1alpha1namespaced-pod-preset
  replace-storage-v1alpha1volume-attachment
  replace-storage-v1beta1csi-driver
  replace-storage-v1beta1csi-node
  replace-storage-v1beta1storage-class
  replace-storage-v1beta1volume-attachment
  replace-storage-v1csi-node
  replace-storage-v1storage-class
  replace-storage-v1volume-attachment
  replace-storage-v1volume-attachment-status)
